{
  "id": 1699740,
  "global_id": "Z2lkOi8vaGFja2Vyb25lL1JlcG9ydC8xNjk5NzQw",
  "url": "https://hackerone.com/reports/1699740",
  "title": "nextcloudcmd incorrectly trusts bad TLS certificates",
  "state": "Closed",
  "substate": "resolved",
  "severity_rating": "low",
  "readable_substate": "Resolved",
  "created_at": "2022-09-14T07:53:20.250Z",
  "submitted_at": "2022-09-14T07:53:20.277Z",
  "is_member_of_team?": false,
  "is_organization_group_member?": false,
  "reporter": {
    "disabled": false,
    "username": "tobiaskaminsky",
    "url": "/tobiaskaminsky",
    "profile_picture_urls": {
      "small": "/assets/avatars/default-25f7248a18bdf9e2dc8310319b148d66cff430fa0fade6c5f25fee1b8d7f27ed.png"
    },
    "is_me?": false,
    "cleared": false,
    "verified": false,
    "hackerone_triager": false,
    "hacker_mediation": false
  },
  "team": {
    "id": 13291,
    "url": "https://hackerone.com/nextcloud",
    "handle": "nextcloud",
    "profile_picture_urls": {
      "small": "https://profile-photos.hackerone-user-content.com/variants/tnqlkt8d6fcch8hj8brdjp8nw864/d3dc6b2d7e2dc3657e8861b0d7e2dfca1a6d513dd784c613f4e56738907cea98",
      "medium": "https://profile-photos.hackerone-user-content.com/variants/tnqlkt8d6fcch8hj8brdjp8nw864/5136ed9b2fa7c4d4abbf39fb971047c62d98ec4740a88eb55d7e26373250a937"
    },
    "permissions": [],
    "submission_state": "open",
    "default_currency": "usd",
    "awards_miles": false,
    "offers_bounties": true,
    "state": "public_mode",
    "only_cleared_hackers": false,
    "pentest_feature_enabled?": false,
    "profile": {
      "name": "Nextcloud",
      "twitter_handle": "nextclouders",
      "website": "https://nextcloud.com",
      "about": "Access, share and protect your files, calendars, contacts, communication & more at home and in your enterprise."
    }
  },
  "has_bounty?": false,
  "in_validation?": false,
  "can_view_team": true,
  "can_view_report": true,
  "is_external_bug": false,
  "is_published": false,
  "is_participant": false,
  "has_collaborators": false,
  "submitted_by_team_member": true,
  "stage": 4,
  "public": true,
  "visibility": "full",
  "cve_ids": [
    "CVE-2022-39334"
  ],
  "singular_disclosure_disabled": false,
  "disclosed_at": "2022-12-25T11:32:16.504Z",
  "bug_reporter_agreed_on_going_public_at": null,
  "team_member_agreed_on_going_public_at": "2022-11-25T11:32:13.657Z",
  "comments_closed?": false,
  "facebook_team?": false,
  "team_private?": false,
  "vulnerability_information": "Ref: https://github.com/nextcloud/desktop/issues/4927\n\n### Bug description\n\nI have a self hosted Nextcloud instance using my own private CA for TLS certs.  When running `nextcloudcmd` without the `--trust`, it disregards the cert validation failure as \"This is not an actual error\" and proceeds with the sync anyway.  I expected it to reject the untrusted server cert and assume it is a MITM attack:\n\n```\n# nextcloudcmd --non-interactive -n ~/Nextcloud https://nextcloud.lan\n09-10 12:25:54:348 [ info nextcloud.sync.accessmanager ]:\t2 \"\" \"https://nextcloud.lan/ocs/v1.php/cloud/capabilities?format=json\" has X-Request-ID \"18ff47a0-a482-4456-a489-7aa747170c58\"\n09-10 12:25:54:348 [ info nextcloud.sync.networkjob ]:\tOCC::JsonApiJob created for \"https://nextcloud.lan\" + \"ocs/v1.php/cloud/capabilities\" \"\"\n09-10 12:25:54:545 [ info nextcloud.sync.account ]:\t\"SSL-Errors happened for url  \\\"https://nextcloud.lan/ocs/v1.php/cloud/capabilities?format=json\\\" \\tError in  QSslCertificate(\\\"3\\\", [REDACTED] : \\\"The root certificate of the certificate chain is self-signed, and untrusted\\\" ( \\\"The root certificate of the certificate chain is self-signed, and untrusted\\\" ) \\n \" Certs are known and trusted! This is not an actual error.\n09-10 12:25:54:871 [ info nextcloud.sync.networkjob.jsonapi ]:\tJsonApiJob of QUrl(\"https://nextcloud.lan/ocs/v1.php/cloud/capabilities?format=json\") FINISHED WITH STATUS \"OK\"\n```\n\nAfter [adding the root CA cert to the system's trust store](https://ubuntu.com/server/docs/security-trust-store) the validation passes and the warning goes away.\n\nI am running the latest `nextcloud-desktop-cmd` package, version `2.6.2-1build1`, on Ubuntu Server 20.04.2 LTS.\n\nI did not see this problem in the [NextCloud CVE list](https://www.cvedetails.com/vulnerability-list/vendor_id-15913/product_id-34622/Nextcloud-Nextcloud.htm).\n\n### Steps to reproduce\n\nRun `nextcloudcmd` against a server that has a TLS cert that the system won't validate.\n\n### Expected behavior\n\nAbort the operation if the server's TLS cert cannot be validated, unless `--trust` is specified to explicitly override the security checks.\n\n### Which files are affected by this bug\n\nsrc/libsync/account.cpp\n\n### Operating system\n\nLinux\n\n### Which version of the operating system you are running.\n\nUbuntu 20.04.2 LTS\n\n### Package\n\nDistro package manager\n\n### Nextcloud Server version\n\n24.0.3\n\n### Nextcloud Desktop Client version\n\n2.6.2-1build1\n\n### Is this bug present after an update or on a fresh install?\n\nFresh desktop client install\n\n### Are you using the Nextcloud Server Encryption module?\n\nEncryption is Disabled\n\n### Are you using an external user-backend?\n\n- [X] Default internal user-backend\n- [ ] LDAP/ Active Directory\n- [ ] SSO - SAML\n- [ ] Other\n\n## Impact\n\nPossible MITM",
  "weakness": {
    "id": 28,
    "name": "Improper Certificate Validation"
  },
  "original_report_id": null,
  "original_report_url": null,
  "attachments": [],
  "allow_singular_disclosure_at": "2022-12-25T11:32:13.776Z",
  "allow_singular_disclosure_after": -35866685.789471135,
  "singular_disclosure_allowed": true,
  "vote_count": 9,
  "voters": [
    "jumpydata",
    "shreyaschavhan",
    "zy9ard3",
    "shubham_srt",
    "khizer47",
    "shivammusic",
    "t3chtonic",
    "meispi",
    "joriki"
  ],
  "severity": {
    "rating": "low",
    "score": 2.8,
    "author_type": "Team",
    "metrics": {
      "attack_vector": "local",
      "attack_complexity": "low",
      "privileges_required": "low",
      "user_interaction": "required",
      "scope": "unchanged",
      "confidentiality": "low",
      "integrity": "none",
      "availability": "none"
    }
  },
  "structured_scope": {
    "databaseId": 77,
    "asset_type": "DOWNLOADABLE_EXECUTABLES",
    "asset_identifier": "Desktop Client",
    "max_severity": "critical"
  },
  "abilities": {
    "assignable_team_members": [],
    "assignable_team_member_groups": []
  },
  "summaries": [
    {
      "id": 207627,
      "category": "team",
      "content": "Security advisory at https://github.com/nextcloud/security-advisories/security/advisories/GHSA-82xx-98xv-4jxv",
      "user": {
        "id": 89223,
        "username": "nickvergessen",
        "name": "Joas Schilling",
        "bio": "",
        "cleared": false,
        "verified": false,
        "website": null,
        "location": "Germany",
        "created_at": "2016-07-01T08:17:59.061Z",
        "url": "https://hackerone.com/nickvergessen",
        "hackerone_triager": false,
        "hackerone_employee": false,
        "user_type": "company",
        "profile_picture_urls": {
          "small": "https://profile-photos.hackerone-user-content.com/variants/5DBbeB7om4ZiKgskrEoeTyGH/d3dc6b2d7e2dc3657e8861b0d7e2dfca1a6d513dd784c613f4e56738907cea98",
          "medium": "https://profile-photos.hackerone-user-content.com/variants/5DBbeB7om4ZiKgskrEoeTyGH/5136ed9b2fa7c4d4abbf39fb971047c62d98ec4740a88eb55d7e26373250a937",
          "xtralarge": "https://profile-photos.hackerone-user-content.com/variants/5DBbeB7om4ZiKgskrEoeTyGH/60f411638706d89ae3052af6fe8b88fa9a798e291deee40f6a22e81418d78d5f"
        }
      },
      "can_view?": true,
      "can_create?": false,
      "attachments": []
    },
    {
      "category": "researcher",
      "can_view?": true,
      "can_create?": false
    }
  ]
}
